# Generated by Django 3.1.6 on 2021-02-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_qq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_id', models.CharField(max_length=21)),
                ('supplier', models.CharField(max_length=200)),
                ('recharge_user', models.CharField(max_length=10)),
                ('recharge_time', models.DateTimeField(auto_now_add=True)),
                ('recharge_way', models.CharField(max_length=5)),
                ('recharge_money', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
