# Generated by Django 3.1.6 on 2021-02-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_medicine_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='create_data',
            field=models.DateField(default=datetime.datetime(2021, 2, 18, 14, 26, 28, 125161)),
        ),
    ]
